### ISSUE TITLE
cool project!

### ISSUE THREAD

**Issue by aquynh** [karttoon/shellbug#1]
just found your little handy tools, nice works! we linked to Shellbug & asm_buddy from our websites now: http://capstone-engine.org/showcase.html, http://keystone-engine.org/showcase

keep it up, cheers.

**Comment by aquynh** [comment]
ah, you are using Capstone & Unicorn, but not Keystone (as in your README). we updated this instead: http://www.unicorn-engine.org/showcase/

**Comment by karttoon** [comment]
D'oh - sorry, I updated it :) Nice catch and thanks for the amazing tools!

**Comment by aquynh** [comment]
Is it better to let user directly pass asm code to shellbug, rather than
only support binary input? On the other word, include asm_buddy into this
tool.

Cheers
